version: "3"
services:
  # 注册中心 Zookeeper
  registry:
    image: zookeeper
    user: root
    restart: always
    privileged: true
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      TZ: Asia/Shanghai
    volumes:
      # - ./zookeeper/conf/zoo.cfg:/conf/zoo.cfg
      - ./zookeeper/conf:/conf
      - ./zookeeper/data:/data
      - ./zookeeper/logs:/datalog
  # 数据面板 dubbo-admin
  dubbo-admin:
    image: apache/dubbo-admin
    user: root
    restart: always
    ports:
      - 38080:38080
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - registry
    volumes:
      - ./dubbo_admin:/config
  shenyu-bootstrap:
    image: apache/shenyu-bootstrap:latest
    container_name: shenyu-bootstrap
    ports:
      - "9195:9195"
    volumes:
      - ./shenyu-bootstrap/logs/:/opt/shenyu-bootstrap/logs
      - ./shenyu-bootstrap/conf/:/opt/shenyu-bootstrap/conf
    depends_on:
      - shenyu-admin
    environment:
      - shenyu.sync.websocket.urls=ws://shenyu-admin:9095/websocket
    healthcheck:
      test: [ "CMD", "wget", "http://shenyu-bootstrap:9195/actuator/health" ]
      timeout: 2s
      retries: 30
  shenyu-admin:
    image: apache/shenyu-admin:latest
    container_name: shenyu-admin
    volumes:
      - ./shenyu-admin/logs/:/opt/shenyu-admin/logs
      - ./shenyu-admin/conf/:/opt/shenyu-admin/conf
    ports:
      - "9095:9095"
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://shenyu-admin:9095/actuator/health | grep UP || exit 1" ]
      timeout: 2s
      retries: 30

